# Generated by Django 6.0.5 on 2026-05-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('version_code', models.PositiveIntegerField(unique=True)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='releases/')),
                ('apk_url_externe', models.URLField(blank=True, help_text='URL externe si APK hébergé ailleurs')),
                ('changelog', models.TextField(blank=True, help_text='Notes de version (HTML ou texte)')),
                ('est_active', models.BooleanField(default=True, help_text="Seule la version active est retournée par l'API")),
                ('publiee_le', models.DateTimeField(auto_now_add=True)),
                ('obligatoire', models.BooleanField(default=False, help_text='Si True, force la mise à jour')),
            ],
            options={
                'verbose_name': 'Version application',
                'verbose_name_plural': 'Versions application',
                'ordering': ['-version_code'],
            },
        ),
    ]
