# Generated by Django 6.0.5 on 2026-05-16 05:59

import apps.smartdocs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(default='fa-file', help_text='Classe FontAwesome', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Patrimoine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('annee_construction', models.PositiveIntegerField(blank=True, null=True)),
                ('surface_totale', models.DecimalField(blank=True, decimal_places=2, help_text='m²', max_digits=10, null=True)),
                ('fichier_ifc', models.FileField(blank=True, null=True, upload_to='patrimoines/ifc/')),
                ('fichier_json', models.FileField(blank=True, null=True, upload_to='patrimoines/json/')),
                ('statut_conversion', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'Conversion en cours'), ('ok', 'Converti'), ('erreur', 'Erreur de conversion')], default='en_attente', max_length=20)),
                ('erreur_conversion', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patrimoines/photos/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimoines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrimoine',
                'verbose_name_plural': 'Patrimoines',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.IntegerField(default=0)),
                ('ifc_guid', models.CharField(blank=True, max_length=100)),
                ('patrimoine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etages', to='smartdocs.patrimoine')),
            ],
            options={
                'verbose_name': 'Étage',
                'verbose_name_plural': 'Étages',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, help_text='m²', max_digits=8, null=True)),
                ('ifc_guid', models.CharField(blank=True, max_length=100)),
                ('usage', models.CharField(blank=True, max_length=100)),
                ('etage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='smartdocs.etage')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to=apps.smartdocs.models.document_upload_path)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, help_text='ex. v2.1', max_length=20)),
                ('date_doc', models.DateField(blank=True, help_text='Date du document', null=True)),
                ('uploade_le', models.DateTimeField(auto_now_add=True)),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etage', models.ForeignKey(blank=True, help_text='Laisser vide pour un document lié au bâtiment entier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='smartdocs.etage')),
                ('patrimoine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='smartdocs.patrimoine')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='smartdocs.typedocument')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploade_le'],
            },
        ),
    ]
