# Generated by Django 6.0.5 on 2026-05-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs', '0002_site_ged_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_doc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='etage',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un document global', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='smartdocs.etage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patrimoine',
            name='surface_totale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m² — calculé automatiquement depuis IFC', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='icone',
            field=models.CharField(default='fa-file', max_length=50),
        ),
    ]
