# Generated by Django 6.0.5 on 2026-05-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs', '0003_alter_document_date_doc_alter_document_etage_and_more'),
        ('smartdocs', '0003_equipement_details'),
    ]

    operations = [
    ]
