# Generated by Django 6.0.5 on 2026-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs', '0004_merge_20260520_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipementouverture',
            options={'ordering': ['etage__niveau', 'type_element', 'nomenclature', 'nom'], 'verbose_name': 'Équipement / Ouverture'},
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='materiau',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='nom',
            field=models.CharField(help_text='Nom IFC brut', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='nomenclature',
            field=models.CharField(blank=True, help_text='Nom lisible (ex: Porte int. bois, Fenêtre oscillo-battant)', max_length=300),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='puissance',
            field=models.CharField(blank=True, help_text='Ex: 60W, 2×36W', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='type_element',
            field=models.CharField(choices=[('ouverture', 'Ouverture (porte / fenêtre)'), ('sanitaire', 'Sanitaire'), ('equipement', 'Équipement'), ('electrique', 'Électrique / Éclairage'), ('mep', 'MEP / Technique'), ('protection', 'Protection / Garde-corps'), ('mobilier', 'Mobilier'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipementouverture',
            name='vitrage',
            field=models.CharField(blank=True, help_text='Simple, Double, Triple vitrage', max_length=100),
        ),
    ]
