# Generated by Django 6.0.5 on 2026-05-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs', '0004_revetement_enrichi'),
        ('smartdocs', '0005_alter_equipementouverture_options_and_more'),
    ]

    operations = [
    ]
