# Generated by Django 6.0.5 on 2026-05-22 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdocs', '0006_merge_20260521_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revetementmur',
            name='nature',
            field=models.CharField(blank=True, help_text='Carrelage, Parquet, Enduit, Peinture, Faux-plafond…', max_length=150),
        ),
        migrations.AlterField(
            model_name='revetementmur',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revetements', to='smartdocs.piece'),
        ),
    ]
