from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import apps.construction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('type_projet', models.CharField(choices=[('batiment','Bâtiment neuf'),('renovation','Rénovation'),('amenagement','Aménagement'),('vrd','VRD / Génie civil'),('autre','Autre')], default='batiment', max_length=20)),
                ('statut', models.CharField(choices=[('prospection','Prospection'),('etude','En étude'),('en_cours','En cours'),('reception','Réception travaux'),('termine','Terminé'),('suspendu','Suspendu')], default='etude', max_length=20)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_contact', models.CharField(blank=True, max_length=100)),
                ('client_email', models.EmailField(blank=True)),
                ('client_tel', models.CharField(blank=True, max_length=30)),
                ('client_adresse', models.TextField(blank=True)),
                ('adresse_chantier', models.TextField(blank=True)),
                ('description_courte', models.CharField(blank=True, max_length=300)),
                ('cahier_des_charges', models.TextField(blank=True)),
                ('visible_vitrine', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_contractuel', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to='auth.user')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_geres', to='auth.user')),
            ],
            options={'verbose_name':'Projet','verbose_name_plural':'Projets','ordering':['-cree_le']},
        ),
        migrations.CreateModel(
            name='TacheGantt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('a_faire','À faire'),('en_cours','En cours'),('termine','Terminée'),('bloquee','Bloquée'),('annulee','Annulée')], default='a_faire', max_length=20)),
                ('priorite', models.CharField(choices=[('haute','Haute'),('normale','Normale'),('basse','Basse')], default='normale', max_length=10)),
                ('avancement', models.PositiveSmallIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('couleur', models.CharField(default='#2196f3', max_length=7)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='construction.projet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='construction.tachegantt')),
                ('dependances', models.ManyToManyField(blank=True, related_name='bloquantes', to='construction.tachegantt')),
                ('assignee_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to='auth.user')),
            ],
            options={'ordering':['ordre','date_debut']},
        ),
        migrations.CreateModel(name='PhotoProjet', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('image', models.ImageField(upload_to=apps.construction.models.projet_photo_path)),
            ('legende', models.CharField(blank=True, max_length=200)),
            ('principale', models.BooleanField(default=False)),
            ('ordre', models.PositiveSmallIntegerField(default=0)),
            ('ajoutee_le', models.DateTimeField(auto_now_add=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='construction.projet')),
        ], options={'ordering':['ordre','ajoutee_le']}),
        migrations.CreateModel(name='DocumentClient', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('type_doc', models.CharField(choices=[('cdc','Cahier des charges'),('plan','Plan / Esquisse'),('photo','Photo de référence'),('contrat','Contrat / Devis signé'),('autre','Autre')], default='cdc', max_length=20)),
            ('titre', models.CharField(max_length=255)),
            ('fichier', models.FileField(upload_to=apps.construction.models.projet_doc_client_path)),
            ('description', models.TextField(blank=True)),
            ('version', models.CharField(blank=True, max_length=20)),
            ('date_reception', models.DateField(default=django.utils.timezone.now)),
            ('cree_le', models.DateTimeField(auto_now_add=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_client', to='construction.projet')),
            ('recu_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
        ], options={'ordering':['-date_reception']}),
        migrations.CreateModel(name='DocumentChantier', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('type_doc', models.CharField(choices=[('plan_exe',"Plan d'exécution"),('note_calc','Note de calcul'),('doe','DOE'),('pv','PV'),('metrage','Métré'),('planning','Planning'),('securite','Plan de sécurité'),('reception','Fiche de réception'),('autre','Autre')], default='plan_exe', max_length=20)),
            ('phase', models.CharField(choices=[('etude','Phase étude'),('exe','Phase exécution'),('reception','Réception'),('garantie','Garantie')], default='exe', max_length=20)),
            ('titre', models.CharField(max_length=255)),
            ('fichier', models.FileField(upload_to=apps.construction.models.projet_doc_chantier_path)),
            ('description', models.TextField(blank=True)),
            ('version', models.CharField(blank=True, default='v1.0', max_length=20)),
            ('indice', models.CharField(blank=True, max_length=10)),
            ('date_doc', models.DateField(default=django.utils.timezone.now)),
            ('valide', models.BooleanField(default=False)),
            ('cree_le', models.DateTimeField(auto_now_add=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_chantier', to='construction.projet')),
            ('produit_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
        ], options={'ordering':['-date_doc','type_doc']}),
        migrations.CreateModel(name='LigneBudget', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('categorie', models.CharField(choices=[('main_oeuvre',"Main d'œuvre"),('materiaux','Matériaux'),('equipement','Équipement'),('sous_traitant','Sous-traitance'),('etude','Études'),('divers','Divers')], max_length=20)),
            ('designation', models.CharField(max_length=255)),
            ('unite', models.CharField(blank=True, max_length=30)),
            ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
            ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=14)),
            ('montant_reel', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('note', models.TextField(blank=True)),
            ('cree_le', models.DateTimeField(auto_now_add=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='construction.projet')),
            ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_budget', to='construction.tachegantt')),
        ], options={'ordering':['categorie','designation']}),
        migrations.CreateModel(name='BonCommande', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('numero', models.CharField(blank=True, max_length=30, unique=True)),
            ('statut', models.CharField(choices=[('brouillon','Brouillon'),('envoye','Envoyé'),('valide','Validé'),('livre','Livré'),('annule','Annulé')], default='brouillon', max_length=20)),
            ('fournisseur_nom', models.CharField(max_length=200)),
            ('fournisseur_contact', models.CharField(blank=True, max_length=100)),
            ('fournisseur_tel', models.CharField(blank=True, max_length=30)),
            ('date_commande', models.DateField(default=django.utils.timezone.now)),
            ('date_livraison', models.DateField(blank=True, null=True)),
            ('lieu_livraison', models.CharField(blank=True, max_length=200)),
            ('tva_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
            ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('note', models.TextField(blank=True)),
            ('fichier_pdf', models.FileField(blank=True, null=True, upload_to=apps.construction.models.bon_commande_path)),
            ('cree_le', models.DateTimeField(auto_now_add=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='construction.projet')),
            ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
        ], options={'ordering':['-date_commande']}),
        migrations.CreateModel(name='LigneBonCommande', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('designation', models.CharField(max_length=255)),
            ('unite', models.CharField(blank=True, max_length=30)),
            ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
            ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ('montant_ht', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
            ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='construction.boncommande')),
        ]),
        migrations.CreateModel(name='Facture', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('numero', models.CharField(blank=True, max_length=30, unique=True)),
            ('type_facture', models.CharField(choices=[('acompte','Acompte'),('situation','Situation de travaux'),('solde','Facture de solde'),('avoir','Avoir')], default='situation', max_length=20)),
            ('statut', models.CharField(choices=[('brouillon','Brouillon'),('envoyee','Envoyée'),('payee','Payée'),('partielle','Paiement partiel'),('retard','En retard'),('annulee','Annulée')], default='brouillon', max_length=20)),
            ('emetteur_nom', models.CharField(default='R-CYBER BTP', max_length=200)),
            ('emetteur_adresse', models.TextField(blank=True)),
            ('emetteur_tel', models.CharField(blank=True, max_length=30)),
            ('emetteur_email', models.EmailField(blank=True)),
            ('emetteur_nif', models.CharField(blank=True, max_length=50)),
            ('client_nom', models.CharField(max_length=200)),
            ('client_adresse', models.TextField(blank=True)),
            ('date_emission', models.DateField(default=django.utils.timezone.now)),
            ('date_echeance', models.DateField(blank=True, null=True)),
            ('date_paiement', models.DateField(blank=True, null=True)),
            ('tva_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
            ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('pct_avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ('montant_precedent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('objet', models.CharField(blank=True, max_length=300)),
            ('conditions_paiement', models.TextField(blank=True)),
            ('note', models.TextField(blank=True)),
            ('cree_le', models.DateTimeField(auto_now_add=True)),
            ('modifie_le', models.DateTimeField(auto_now=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='construction.projet')),
            ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
        ], options={'ordering':['-date_emission']}),
        migrations.CreateModel(name='LigneFacture', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('designation', models.CharField(max_length=255)),
            ('unite', models.CharField(blank=True, max_length=30)),
            ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
            ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='construction.facture')),
            ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.tachegantt')),
        ]),
        migrations.CreateModel(name='RapportActivite', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('type_rapport', models.CharField(choices=[('journalier','Journalier'),('hebdo','Hebdomadaire'),('mensuel','Mensuel'),('tache','Fin de tâche'),('situation','Situation de travaux')], default='hebdo', max_length=20)),
            ('titre', models.CharField(max_length=255)),
            ('periode_debut', models.DateField()),
            ('periode_fin', models.DateField()),
            ('travaux_realises', models.TextField()),
            ('observations', models.TextField(blank=True)),
            ('travaux_prevus', models.TextField(blank=True)),
            ('avancement_constate', models.PositiveSmallIntegerField(default=0)),
            ('nb_ouvriers', models.PositiveSmallIntegerField(default=0)),
            ('nb_journees', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
            ('fichier', models.FileField(blank=True, null=True, upload_to=apps.construction.models.rapport_path)),
            ('montant_a_facturer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ('cree_le', models.DateTimeField(auto_now_add=True)),
            ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='construction.projet')),
            ('redige_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ('taches_concernees', models.ManyToManyField(blank=True, related_name='rapports', to='construction.tachegantt')),
            ('facture_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_lies', to='construction.facture')),
        ], options={'ordering':['-periode_fin']}),
    ]
