# Generated by Django 6.0.5 on 2026-05-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boncommande',
            options={'ordering': ['-date_commande'], 'verbose_name': 'Bon de commande', 'verbose_name_plural': 'Bons de commande'},
        ),
        migrations.AlterModelOptions(
            name='documentchantier',
            options={'ordering': ['-date_doc', 'type_doc'], 'verbose_name': 'Document chantier', 'verbose_name_plural': 'Documents chantier'},
        ),
        migrations.AlterModelOptions(
            name='documentclient',
            options={'ordering': ['-date_reception'], 'verbose_name': 'Document client', 'verbose_name_plural': 'Documents clients'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='ligneboncommande',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='lignebudget',
            options={'ordering': ['categorie', 'designation'], 'verbose_name': 'Ligne budget', 'verbose_name_plural': 'Lignes budget'},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='photoprojet',
            options={'ordering': ['ordre', 'ajoutee_le'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='rapportactivite',
            options={'ordering': ['-periode_fin'], 'verbose_name': "Rapport d'activité", 'verbose_name_plural': "Rapports d'activité"},
        ),
        migrations.AlterModelOptions(
            name='tachegantt',
            options={'ordering': ['ordre', 'date_debut'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('valide', 'Validé / Accepté'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentchantier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentchantier',
            name='indice',
            field=models.CharField(blank=True, help_text='ex. A, B, C…', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentchantier',
            name='type_doc',
            field=models.CharField(choices=[('plan_exe', "Plan d'exécution"), ('note_calc', 'Note de calcul'), ('doe', 'DOE / Dossier des ouvrages exécutés'), ('pv', 'PV / Procès-verbal'), ('metrage', 'Métré / Devis quantitatif'), ('planning', 'Planning'), ('securite', 'Plan de sécurité'), ('reception', 'Fiche de réception'), ('autre', 'Autre')], default='plan_exe', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentclient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='emetteur_nif',
            field=models.CharField(blank=True, help_text='NIF / STAT', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_precedent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul déjà facturé', max_digits=14),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, help_text='Généré auto — FAC-2026-001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='pct_avancement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% avancement pour cette situation', max_digits=5),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('acompte', 'Acompte / Appel de fonds'), ('situation', 'Situation de travaux'), ('solde', 'Facture de solde'), ('avoir', 'Avoir')], default='situation', max_length=20),
        ),
        migrations.AlterField(
            model_name='ligneboncommande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignebudget',
            name='categorie',
            field=models.CharField(choices=[('main_oeuvre', "Main d'œuvre"), ('materiaux', 'Matériaux'), ('equipement', 'Équipement / Location'), ('sous_traitant', 'Sous-traitance'), ('etude', 'Études / Bureau'), ('divers', 'Divers / Imprévus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lignebudget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignebudget',
            name='unite',
            field=models.CharField(blank=True, help_text='m², ml, u, forfait…', max_length=30),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photoprojet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='photoprojet',
            name='principale',
            field=models.BooleanField(default=False, help_text='Photo de couverture affichée en vitrine'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='cahier_des_charges',
            field=models.TextField(blank=True, help_text='Ce que le client attendait'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description_courte',
            field=models.CharField(blank=True, help_text='Résumé affiché en vitrine', max_length=300),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='reference',
            field=models.CharField(blank=True, help_text='Générée auto si vide — ex. PROJ-2026-001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='visible_vitrine',
            field=models.BooleanField(default=False, help_text='Afficher sur la page publique'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='montant_a_facturer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant à facturer sur ce rapport', max_digits=14),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='observations',
            field=models.TextField(blank=True, help_text='Problèmes, risques, remarques'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='travaux_prevus',
            field=models.TextField(blank=True, help_text='Prochaine période'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='travaux_realises',
            field=models.TextField(help_text='Travaux effectués pendant la période'),
        ),
        migrations.AlterField(
            model_name='tachegantt',
            name='avancement',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pourcentage 0-100'),
        ),
        migrations.AlterField(
            model_name='tachegantt',
            name='couleur',
            field=models.CharField(default='#2196f3', help_text='Couleur hex pour le Gantt', max_length=7),
        ),
        migrations.AlterField(
            model_name='tachegantt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
