# Generated by Django 6.0.5 on 2026-05-25 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_facture_cree_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseauPert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Réseau PERT initial', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='v1', help_text='ex. v1, v2-révisé, baseline…', max_length=20)),
                ('est_actif', models.BooleanField(default=True, help_text='Réseau de référence actif pour ce projet')),
                ('duree_totale', models.PositiveIntegerField(blank=True, help_text='Durée critique calculée (jours)', null=True)),
                ('calcule_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseaux_pert_crees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseaux_pert', to='construction.projet')),
            ],
            options={
                'verbose_name': 'Réseau PERT',
                'verbose_name_plural': 'Réseaux PERT',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='NoeudPert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Identifiant court — A, B, C…', max_length=10)),
                ('early', models.IntegerField(default=0, help_text='Date début au plus tôt (jours)')),
                ('late', models.IntegerField(blank=True, help_text='Date début au plus tard (jours) — calculé', null=True)),
                ('marge', models.IntegerField(blank=True, help_text='Marge totale = tard − tôt — calculé', null=True)),
                ('est_critique', models.BooleanField(default=False)),
                ('pos_x', models.FloatField(default=0, help_text='Position X sur le canvas')),
                ('pos_y', models.FloatField(default=0, help_text='Position Y sur le canvas')),
                ('tache_gantt', models.ForeignKey(blank=True, help_text='Tâche Gantt associée à ce nœud (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noeuds_pert', to='construction.tachegantt')),
                ('reseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noeuds', to='construction.reseaupert')),
            ],
            options={
                'verbose_name': 'Nœud PERT',
                'verbose_name_plural': 'Nœuds PERT',
                'ordering': ['label'],
                'unique_together': {('reseau', 'label')},
            },
        ),
        migrations.CreateModel(
            name='LienPert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.PositiveIntegerField(default=0, help_text='Durée de la tâche en jours')),
                ('est_critique', models.BooleanField(default=False, help_text='Appartient au chemin critique')),
                ('noeud_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_sortants', to='construction.noeudpert')),
                ('noeud_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_entrants', to='construction.noeudpert')),
                ('reseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens', to='construction.reseaupert')),
            ],
            options={
                'verbose_name': 'Lien PERT',
                'verbose_name_plural': 'Liens PERT',
                'unique_together': {('reseau', 'noeud_from', 'noeud_to')},
            },
        ),
    ]
