# Generated by Django 6.0.5 on 2026-05-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_boncommande_options_and_more'),
        ('construction', '003_add_service_tag_migration'),
    ]

    operations = [
    ]
