# Generated by Django 6.0.5 on 2026-05-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartdocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage_actif', models.IntegerField(blank=True, help_text="pk de l'étage filtré, null = tout afficher", null=True)),
                ('camera_state', models.JSONField(blank=True, default=dict, help_text='Position/orientation caméra Three.js')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('patrimoine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_viewer', to='smartdocs.patrimoine')),
            ],
            options={
                'verbose_name': 'Session viewer',
                'verbose_name_plural': 'Sessions viewer',
                'ordering': ['-cree_le'],
            },
        ),
    ]
