# Generated by Django 6.0.5 on 2026-05-23 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_dev', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-date_ouvert', 'severite'], 'verbose_name': 'Bug / Demande', 'verbose_name_plural': 'Bugs / Demandes'},
        ),
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date_devis'], 'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['categorie', '-modifie_le'], 'verbose_name': 'Documentation', 'verbose_name_plural': 'Documentations'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='lignedevis',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='lignefacture',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='livrable',
            options={'ordering': ['-date_livraison', 'type_livrable'], 'verbose_name': 'Livrable', 'verbose_name_plural': 'Livrables'},
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['ordre', 'cree_le'], 'verbose_name': 'Tâche', 'verbose_name_plural': 'Tâches'},
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(help_text='Description détaillée du problème'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='environnement',
            field=models.CharField(blank=True, help_text='OS, navigateur, version…', max_length=200),
        ),
        migrations.AlterField(
            model_name='bug',
            name='etapes_repro',
            field=models.TextField(blank=True, help_text='Étapes pour reproduire'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='rapporte_par',
            field=models.CharField(blank=True, help_text='Nom du client ou utilisateur', max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='solution',
            field=models.TextField(blank=True, help_text='Solution apportée'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_ref',
            field=models.CharField(blank=True, help_text='Référence client partagée (ex. construction)', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_dev_devis_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='contenu',
            field=models.TextField(help_text='Contenu Markdown ou texte brut'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='publie',
            field=models.BooleanField(default=False, help_text='Visible par le client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_dev_factures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='jalon',
            field=models.CharField(blank=True, help_text='ex. Livraison phase 1, Recette validée…', max_length=200),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='changelog',
            field=models.TextField(blank=True, help_text='Notes de version'),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='url_externe',
            field=models.URLField(blank=True, help_text='Lien release GitHub, CDN…'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='cahier_charges',
            field=models.TextField(blank=True, help_text='Besoins fonctionnels du client'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='repo_url',
            field=models.URLField(blank=True, help_text='GitHub / GitLab / URL du projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='stack_technique',
            field=models.CharField(blank=True, help_text='ex. Python 3.12, Django 5, PostgreSQL, React…', max_length=300),
        ),
        migrations.AlterField(
            model_name='projet',
            name='url_prod',
            field=models.URLField(blank=True, help_text='URL de production'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='url_recette',
            field=models.URLField(blank=True, help_text='URL de recette / staging'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
