# Generated by Django 6.0.5 on 2026-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau_etude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date_devis'], 'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AlterModelOptions(
            name='documententree',
            options={'ordering': ['-date_reception'], 'verbose_name': "Document d'entrée", 'verbose_name_plural': "Documents d'entrée"},
        ),
        migrations.AlterModelOptions(
            name='lignedevis',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='notecalcul',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Note de calcul', 'verbose_name_plural': 'Notes de calcul'},
        ),
        migrations.AlterModelOptions(
            name='planlivrable',
            options={'ordering': ['-date_doc', 'type_doc'], 'verbose_name': 'Livrable', 'verbose_name_plural': 'Livrables'},
        ),
        migrations.AlterModelOptions(
            name='reunion',
            options={'ordering': ['-date_reunion'], 'verbose_name': 'Réunion', 'verbose_name_plural': 'Réunions'},
        ),
        migrations.AlterField(
            model_name='devis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documententree',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_rendu',
            field=models.DateField(blank=True, help_text='Date de rendu prévue', null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, help_text='Objet de la mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='objectifs',
            field=models.TextField(blank=True, help_text='Objectifs techniques attendus'),
        ),
        migrations.AlterField(
            model_name='notecalcul',
            name='hypotheses',
            field=models.TextField(blank=True, help_text='Hypothèses de calcul'),
        ),
        migrations.AlterField(
            model_name='notecalcul',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notecalcul',
            name='logiciel',
            field=models.CharField(blank=True, help_text='ex. Robot, RDM6, Excel…', max_length=100),
        ),
        migrations.AlterField(
            model_name='notecalcul',
            name='methodologie',
            field=models.TextField(blank=True, help_text='Méthode / normes utilisées'),
        ),
        migrations.AlterField(
            model_name='notecalcul',
            name='norme_ref',
            field=models.CharField(blank=True, help_text='ex. Eurocode 2, BAEL 91…', max_length=200),
        ),
        migrations.AlterField(
            model_name='notecalcul',
            name='resultats',
            field=models.TextField(blank=True, help_text='Résultats et dimensionnements'),
        ),
        migrations.AlterField(
            model_name='planlivrable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='actions',
            field=models.TextField(blank=True, help_text='Actions à mener (responsable / délai)'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='participants',
            field=models.TextField(blank=True, help_text='Liste des participants (un par ligne)'),
        ),
    ]
