# Generated by Django 6.0.5 on 2026-05-23 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau_etude', '0002_alter_devis_options_alter_documententree_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_etude_devis_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
