"""
MOREX Devis BTP — Migration initiale auto-générée.
Exécuter : python manage.py migrate
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('unite', models.CharField(help_text='u, m3, m2, kg, sac, ml\u2026', max_length=20)),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frais_manutention', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frais_transport', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taux_chute', models.DecimalField(decimal_places=2, default=0, help_text='Taux de chute et perte en %', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Mat\u00e9riau', 'verbose_name_plural': 'Mat\u00e9riaux', 'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ex. BO-01, MR-04', max_length=20, unique=True)),
                ('categorie', models.CharField(choices=[('BETON', 'B\u00e9ton'), ('MORTIER', 'Mortier'), ('ENDUIT', 'Enduit'), ('AUTRE', 'Autre')], default='BETON', max_length=10)),
                ('dosage_kg', models.IntegerField(default=300)),
                ('choix_liant', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sable_m3', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('gravillon_m3', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('eau_litres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ciment_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('chaux_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('acier_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fil_recuit_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={'verbose_name': 'Dosage', 'verbose_name_plural': 'Dosages', 'ordering': ['categorie', 'dosage_kg']},
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('finalise', 'Finalis\u00e9'), ('envoye', 'Envoy\u00e9 au client'), ('accepte', 'Accept\u00e9'), ('refuse', 'Refus\u00e9'), ('archive', 'Archiv\u00e9')], default='brouillon', max_length=15)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('bureau_etude', "Bureau d'\u00e9tude"), ('construction', 'Construction')], default='direct', max_length=20)),
                ('mission_id_ref', models.IntegerField(blank=True, null=True)),
                ('projet_id_ref', models.IntegerField(blank=True, null=True)),
                ('client_nom', models.CharField(max_length=200)),
                ('client_adresse', models.TextField(blank=True)),
                ('client_tel', models.CharField(blank=True, max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('maitre_ouvrage', models.CharField(blank=True, max_length=200)),
                ('adresse_chantier', models.TextField(blank=True)),
                ('duree_chantier_mois', models.DecimalField(decimal_places=1, default=6, max_digits=5)),
                ('mode_mo', models.CharField(choices=[('horaire', 'Base horaire (PHMO)'), ('forfait', 'Forfaitaire par t\u00e2che')], default='horaire', max_length=10)),
                ('taux_aleas', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('taux_benefice', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('montant_debourse_sec', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('emetteur_nom', models.CharField(default='MOREX BTP', max_length=200)),
                ('emetteur_adresse', models.TextField(blank=True)),
                ('emetteur_tel', models.CharField(blank=True, max_length=30)),
                ('emetteur_email', models.EmailField(blank=True, max_length=254)),
                ('emetteur_nif', models.CharField(blank=True, max_length=50)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_devis', models.DateField(default=django.utils.timezone.now)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='devis_btp/%Y/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_btp_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Devis BTP', 'verbose_name_plural': 'Devis BTP', 'ordering': ['-date_devis']},
        ),
        migrations.CreateModel(
            name='RecapAvantMetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(default='m3', max_length=5)),
                ('qam', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recap_am', to='devis_btp.devis')),
                ('dosage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_btp.dosage')),
            ],
            options={'verbose_name': 'R\u00e9cap avant-m\u00e9tr\u00e9', 'verbose_name_plural': 'R\u00e9cap avant-m\u00e9tr\u00e9s', 'ordering': ['ordre', 'numero'], 'unique_together': {('devis', 'designation')}},
        ),
        migrations.CreateModel(
            name='LigneAvantMetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvrage_num', models.CharField(blank=True, max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('repere', models.CharField(blank=True, max_length=30)),
                ('unite', models.CharField(choices=[('m3', 'm\xb3'), ('m2', 'm\xb2'), ('ml', 'ml'), ('u', 'u'), ('kg', 'kg'), ('sac', 'sac'), ('t', 'tonne')], default='m3', max_length=5)),
                ('signe', models.CharField(choices=[('ajouter', '\u00c0 ajouter'), ('deduire', '\u00c0 d\u00e9duire')], default='ajouter', max_length=10)),
                ('nps', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('longueur', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('largeur', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('aux', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12)),
                ('partiel', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12)),
                ('qam', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avant_metre', to='devis_btp.devis')),
            ],
            options={'verbose_name': 'Ligne avant-m\u00e9tr\u00e9', 'verbose_name_plural': 'Lignes avant-m\u00e9tr\u00e9', 'ordering': ['ordre', 'pk']},
        ),
        migrations.CreateModel(
            name='LigneNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_nette', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('quantite_chute', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature', to='devis_btp.devis')),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devis_btp.materiau')),
                ('recap_am', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_lignes', to='devis_btp.recapavantmetre')),
            ],
            options={'verbose_name': 'Ligne nomenclature', 'verbose_name_plural': 'Lignes nomenclature', 'unique_together': {('devis', 'recap_am', 'materiau')}},
        ),
        migrations.CreateModel(
            name='EquipePHMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('P', 'P \u2014 Personnel de production'), ('H', 'H \u2014 Personnel hautement qualifi\u00e9'), ('M', 'M \u2014 Ma\u00eetrise'), ('O', 'O \u2014 Ouvrier'), ('E', 'E \u2014 Employ\u00e9'), ('C', 'C \u2014 Cadre')], default='O', max_length=2)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_charges', models.DecimalField(decimal_places=2, default=22, max_digits=5)),
                ('nb_jours_mois', models.DecimalField(decimal_places=1, default=26, max_digits=4)),
                ('heures_par_jour', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('heures_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_phmo', to='devis_btp.devis')),
            ],
            options={'verbose_name': '\u00c9quipe PHMO', 'verbose_name_plural': '\u00c9quipes PHMO', 'ordering': ['ordre', 'categorie']},
        ),
        migrations.CreateModel(
            name='TacheForfaitMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(default='fft', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('pu_mo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_mo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_forfait', to='devis_btp.devis')),
            ],
            options={'verbose_name': 'T\u00e2che forfait MO', 'verbose_name_plural': 'T\u00e2ches forfait MO', 'ordering': ['ordre', 'pk']},
        ),
        migrations.CreateModel(
            name='FraisChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('etat_major', "Co\u00fbts \u00e9tat-major du chantier"), ('mo_non_productive', "Main d'\u0153uvre non productive"), ('fonctionnement', 'D\u00e9penses de fonctionnement')], default='fonctionnement', max_length=25)),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(default='mois', max_length=30)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_chantier', to='devis_btp.devis')),
            ],
            options={'verbose_name': 'Frais de chantier', 'verbose_name_plural': 'Frais de chantier', 'ordering': ['categorie', 'ordre']},
        ),
        migrations.CreateModel(
            name='LigneDEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(default='m3', max_length=10)),
                ('qam', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('pu_materiaux', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pu_mo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pu_frais', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_materiaux', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('montant_mo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('montant_frais', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_deps', to='devis_btp.devis')),
                ('recap_am', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_deps', to='devis_btp.recapavantmetre')),
            ],
            options={'verbose_name': 'Ligne DEPS', 'verbose_name_plural': 'Lignes DEPS', 'ordering': ['ordre', 'numero']},
        ),
        migrations.CreateModel(
            name='BonCommandeMateriaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoy\u00e9'), ('valide', 'Valid\u00e9'), ('livre', 'Livr\u00e9'), ('annule', 'Annul\u00e9')], default='brouillon', max_length=15)),
                ('fournisseur_nom', models.CharField(max_length=200)),
                ('fournisseur_tel', models.CharField(blank=True, max_length=30)),
                ('date_commande', models.DateField(default=django.utils.timezone.now)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('lieu_livraison', models.CharField(blank=True, max_length=200)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tva_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='devis_btp.devis')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Bon de commande mat\u00e9riaux', 'verbose_name_plural': 'Bons de commande mat\u00e9riaux', 'ordering': ['-date_commande']},
        ),
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis_btp.boncommandeMateriaux')),
                ('materiau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_btp.materiau')),
            ],
            options={'ordering': ['pk']},
        ),
    ]
