# Generated by Django 6.0.5 on 2026-05-25 17:39

import apps.devis_btp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_btp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions générales'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='emetteur_nif',
            field=models.CharField(blank=True, help_text='NIF / STAT', max_length=50),
        ),
        migrations.AlterField(
            model_name='devis',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.devis_btp.models.devis_pdf_path),
        ),
        migrations.AlterField(
            model_name='devis',
            name='mission_id_ref',
            field=models.IntegerField(blank=True, help_text='PK de la Mission liée (bureau_etude)', null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='projet_id_ref',
            field=models.IntegerField(blank=True, help_text='PK du Projet lié (construction)', null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_aleas',
            field=models.DecimalField(decimal_places=2, default=5, help_text="% d'aléas et imprévus", max_digits=5),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_benefice',
            field=models.DecimalField(decimal_places=2, default=10, help_text='% de bénéfices', max_digits=5),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=20, help_text='% TVA', max_digits=5),
        ),
        migrations.AlterField(
            model_name='devis',
            name='titre',
            field=models.CharField(help_text='Objet du devis', max_length=255),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='acier_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text="kg d'acier HA (béton armé)", max_digits=8),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='chaux_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='kg de chaux (si mortier chaux)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='choix_liant',
            field=models.CharField(blank=True, help_text='ex. CPA 250/315, CHRI 315/400', max_length=100),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='ciment_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='kg de ciment', max_digits=8),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='dosage_kg',
            field=models.IntegerField(default=300, help_text='Dosage en kg de liant par m³'),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='eau_litres',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Litres d'eau", max_digits=8),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='fil_recuit_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='kg de fil recuit', max_digits=8),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='gravillon_m3',
            field=models.DecimalField(decimal_places=3, default=0, help_text='m³ de gravillon', max_digits=6),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='sable_m3',
            field=models.DecimalField(decimal_places=3, default=0, help_text='m³ de sable', max_digits=6),
        ),
        migrations.AlterField(
            model_name='equipephmo',
            name='heures_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Heures totales prévues sur le chantier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipephmo',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, help_text='Salaire de base mensuel brut (Ar)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipephmo',
            name='taux_charges',
            field=models.DecimalField(decimal_places=2, default=22, help_text='Taux charges sociales patronales (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='aux',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Résultat auxiliaire', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='hauteur',
            field=models.DecimalField(decimal_places=3, default=0, help_text='H (m)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='largeur',
            field=models.DecimalField(decimal_places=3, default=0, help_text='l (m)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='longueur',
            field=models.DecimalField(decimal_places=3, default=0, help_text='L (m)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='nps',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Nombre de pièces semblables', max_digits=6),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='ouvrage_num',
            field=models.CharField(blank=True, help_text='ex. 101, 201', max_length=10),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='partiel',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, help_text='NPS × calcul', max_digits=12),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='qam',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Quantité avant-métré définitive', max_digits=14),
        ),
        migrations.AlterField(
            model_name='ligneavantmetre',
            name='repere',
            field=models.CharField(blank=True, help_text='ex. s1, v1, sbp1', max_length=30),
        ),
        migrations.AlterField(
            model_name='lignenomenclature',
            name='quantite_chute',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantité avec chute et perte', max_digits=14),
        ),
        migrations.AlterField(
            model_name='materiau',
            name='prix_fournisseur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix ex-usine ou catalogue fournisseur', max_digits=14),
        ),
        migrations.AlterField(
            model_name='recapavantmetre',
            name='dosage',
            field=models.ForeignKey(blank=True, help_text='Dosage associé pour le calcul des matériaux', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_btp.dosage'),
        ),
        migrations.AlterField(
            model_name='tacheforfaitmo',
            name='pu_mo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire MO forfaitaire (Ar)', max_digits=14),
        ),
    ]
